[package]
name = "futures-lite"
version = "0.1.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "A subset of the futures crate with some additions"
license = "Apache-2.0 OR MIT"

[features]
default = ["std"]
std = []

[dependencies]
futures-core = "0.3.5"
futures-io = { version = "0.3.5", default-features = false, features = ["std"] }
pin-project-lite = "0.1.7"
